// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMAxBYTLQTrQh6gcG6ZG1WUVUuN2tkTOI',
    appId: '1:923215387352:web:ea83f5ed3362e6f58155ad',
    messagingSenderId: '923215387352',
    projectId: 'bodegalert',
    authDomain: 'bodegalert.firebaseapp.com',
    databaseURL: 'https://bodegalert.firebaseio.com',
    storageBucket: 'bodegalert.appspot.com',
    measurementId: 'G-HRKCGSNMF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-L9VmCcYHpQ13Rllrdl0k54Ma5QSiQU',
    appId: '1:923215387352:android:d313b5585a877f408155ad',
    messagingSenderId: '923215387352',
    projectId: 'bodegalert',
    databaseURL: 'https://bodegalert.firebaseio.com',
    storageBucket: 'bodegalert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOZMli04WzhOx7g_XXa3SbVfJuur341-8',
    appId: '1:923215387352:ios:94b10cfe79c013678155ad',
    messagingSenderId: '923215387352',
    projectId: 'bodegalert',
    databaseURL: 'https://bodegalert.firebaseio.com',
    storageBucket: 'bodegalert.appspot.com',
    androidClientId: '923215387352-42re9ud06lt28flp1o8l4jgspf11vvi7.apps.googleusercontent.com',
    iosClientId: '923215387352-ajtg2qkbj90ecvf7uodb73dp8a2hu6f9.apps.googleusercontent.com',
    iosBundleId: 'io.cordova.alarmu',
  );
}
